export const API = {
  GetChunkGraphAI: '/api/graph/chunks/graph/ai',
  GetChunkByIdAI: '/api/graph/chunk/id/ai',
  GetModuleDetails: '/api/graph/module/details',
  GetModuleByName: '/api/graph/module/name',
  GetModuleIssuerPath: '/api/graph/module/issuer_path',
  GetPackageInfo: '/api/package/info',
  GetPackageDependency: '/api/package/dependency',
  GetOverlayAlerts: '/api/alerts/overlay',
  GetLoaderChartData: '/api/loader/chart/data',
  GetDirectoriesLoaders: '/api/loader/directories',
  GetBuildSummary: '/api/build/summary',
  GetAssets: '/api/assets/list',
  GetEntrypoints: '/api/entrypoints/list',
  GetBuildConfig: '/api/build/config',
  GetErrors: '/api/errors/list',
  GetModuleExports: '/api/module/exports',
  GetSideEffects: '/api/module/side-effects',
};
