#!/bin/sh

if [ -f "$HUSKY_SCRIPT" ]; then
    . "$HUSKY_SCRIPT"
    # avoid conflicts in pnpm lock
    # https://7tonshark.com/posts/avoid-conflicts-in-pnpm-lock/
    git config merge.ours.driver true
else
    exit 0
fi
